travis:
  secure:
    BINSTAR_TOKEN: Q5yqrEVEUxPi5fZEXNt5KlXclrYiyaN2Tsrk/WJUykU11WnXTwpw48sKdp4IDW4muVmWAAN1PMiFCMiwiDWy7oxzQV0DffyVfdp8pVvUHsNLG8Qm1x7Gk+VF751tc/iBZd7Alye6jA4MLkFTtHr3Z/8tVgSwUtt0Ix2KR8I+hAQT90kTljNwnfbZivaQl8EdwofcjtycfkKcL57d96vUKuKbjoyaqf6cemNqy0k/Wmv9RKG+JLTQGInWj+VOvev0fVTMh3qw2Ge8F75LJZZgeVXFvksgwP8B9dUBvLrEQ4c/XX7cKcTU9bE0k6OoOdUnYnYRLUuo1Oh71ZwQgeCzMyD+JAX41tmlTDywyLdR5GWDBDd3vYePbkI0cmdAZ30H0VbU1gY5Ie+e3pH3/Y5SQhEpRnmJgFAj7WXgG8xYOt3nlwUVIs7Aplh92/krv9PkvsEW9cAWyx0WGTfK0ACugvBt5rpvMZgUNMnGw0r3Mxu6FZXuP/52GPCEjFNSErMxtYKxdNrOf80TspIVduQ8hhTGObAEzCvwM3TYgx49OC2TwvqRsd0n3QqduasOQRAX7pb6lpaXD/e5yruCMzViqXUekjLif1UkBph6eELpgqKKpyJ3qoPZKVosEjjgytJyGpywlYWX/JOB0uHh00JDpkZSUaJhlM1sl7OrsF2/pMg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
